### ISSUE TITLE
numpy and empty output

### ISSUE THREAD

**Issue by ghost** [saitakturk/portrait_segmentation#1]
typo in test.py, should be import numpy as np 
and I the used 
plt.savefig('foo.png') to save the output which is a white blank image

**Comment by ghost** [comment]
see this input image 
https://upload.wikimedia.org/wikipedia/commons/e/ed/Elon_Musk_Royal_Society.jpg
and blank output
![foo (1)](https://user-images.githubusercontent.com/6818285/58122668-22e38800-7bd8-11e9-9faf-d6d9d4f7c16e.jpg)

**Comment by saitakturk** [comment]
Thank you, I updated the typo. For blank output, you should plt.savefig() function before plt.show() to save output result. Something like this. 
```
plt.imshow(img2)
plt.savefig(`foo.png`)
plt.show()
```
Then it will write result image.

**Comment by ghost** [comment]
thanks i was able to save result now but it is missing pieces
![foo (2)](https://user-images.githubusercontent.com/6818285/58124273-dc902800-7bdb-11e9-950b-d8a74bae6257.jpg)

**Comment by saitakturk** [comment]
The model is trained with the dataset contains <b>"human portrait"</b>,  images not human pose images, therefore the photos that contains face and upper part of human body( Portrait ) will give best output results. However, If I could find a dataset contains human pose masks, then I will train model again and update the repo. <br><b>Portrait definition : a painting, drawing, photograph, or engraving of a person, especially one depicting only the face or head and shoulders.</b>
