### ISSUE TITLE
Binary Mask Data

### ISSUE THREAD

**Issue by rudrarajurahul** [saitakturk/portrait_segmentation#2]
Hi, 

How did you generate the binary mask data for the images?

**Comment by saitakturk** [comment]
The training dataset has already mask with them, which is a single-channel binary image that has 0 and 255-pixel intensities.

**Comment by rudrarajurahul** [comment]
Ok. So what if I want to create my own dataset. Do you how I can mask them?

**Comment by saitakturk** [comment]
I really do not know that maybe photoshop?
